/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MainContract } from "./MainContract";
export type { RecordContract } from "./RecordContract";
export * as factories from "./factories";
export { MainContract__factory } from "./factories/MainContract__factory";
export { RecordContract__factory } from "./factories/RecordContract__factory";
