/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MainContract } from "./MainContract";
export * as factories from "./factories";
export { MainContract__factory } from "./factories/MainContract__factory";
