/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MainContract__factory } from "./MainContract__factory";
export { RecordContract__factory } from "./RecordContract__factory";
